---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (pkg install -y python27 && ln -s /usr/local/bin/python2.7 /usr/bin/python)
      become: true
      changed_when: false
